version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - redis

  redis:
    image: 'redis:latest'

volumes:
  node_modules:
